apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # dont push to dockerhub, prevent default behavior
  local:
    push: false
  #googleCloudBuild:
  #  projectId: mini-stubhub-micro
  artifacts:
    # for dockerHub
    # - image: us.gcr.io/mini-stubhub-micro/auth
    - image: naingaungphyo/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            # where to sync this file to inside of running container
            # . means throw it to the corresponding path inside the container
            dest: .
    - image: naingaungphyo/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            # where to sync this file to inside of running container
            # . means throw it to the corresponding path inside the container
            dest: .
    - image: naingaungphyo/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            # where to sync this file to inside of running container
            # . means throw it to the corresponding path inside the container
            dest: .
    - image: naingaungphyo/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            # where to sync this file to inside of running container
            # . means throw it to the corresponding path inside the container
            dest: .
    - image: naingaungphyo/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            # where to sync this file to inside of running container
            # . means throw it to the corresponding path inside the container
            dest: .
