apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        # name used for logging
        - name: payments
          #  image: us.gcr.io/mini-stubhub-micro/payments
          image: naingaungphyo/payments
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # use pod name as NATS_CLIENT_ID
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://payments-mongo-srv:27017/payments' #payments is databasename
            - name: JWT_KEY # name inside container
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # name of secret
                  key: JWT_KEY # key used when creating secret
---
apiVersion: v1
# creating clusterIP service as default
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
