apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        # name used for logging
        - name: tickets
          #  image: us.gcr.io/mini-stubhub-micro/tickets
          image: naingaungphyo/tickets
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # use pod name as NATS_CLIENT_ID
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: MONGO_URI
              value: 'mongodb://tickets-mongo-srv:27017/tickets' #tickets is databasename
            - name: JWT_KEY # name inside container
              valueFrom:
                secretKeyRef:
                  name: jwt-secret # name of secret
                  key: JWT_KEY # key used when creating secret
---
apiVersion: v1
# creating clusterIP service as default
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
